from pathlib import Path
import base64

def dec(value):
    return base64.b64decode(value).decode('utf-8')

def replace_once(path, old64, new64, label):
    p = Path(path)
    s = p.read_text(encoding='utf-8')
    old = dec(old64)
    new = dec(new64)
    if new in s:
        return
    if old not in s:
        raise SystemExit(f'{label}: anchor not found')
    p.write_text(s.replace(old, new, 1), encoding='utf-8', newline='\n')

replace_once('tutorial.js', 'ICBmdW5jdGlvbiB1cGRhdGVMYXVuY2hlckxhYmVsKGxhdW5jaGVyID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoImRwcm8tdHV0b3JpYWwtbGF1bmNoZXIiKSkgewogICAgaWYgKCFsYXVuY2hlcikgcmV0dXJuOwogICAgY29uc3QgcHJvZ3Jlc3MgPSByZWFkUHJvZ3Jlc3MoKTsKICAgIGxhdW5jaGVyLnRleHRDb250ZW50ID0gcHJvZ3Jlc3MgJiYgIXByb2dyZXNzLmNvbXBsZXRlZCA/ICLmk43kvZzjgqzjgqTjg4nvvIjntprjgY3jgYvjgonvvIkiIDogIuaTjeS9nOOCrOOCpOODiSI7CiAgfQ==', 'ICBmdW5jdGlvbiB1cGRhdGVMYXVuY2hlckxhYmVsKGxhdW5jaGVyID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoImRwcm8tdHV0b3JpYWwtbGF1bmNoZXIiKSkgewogICAgaWYgKCFsYXVuY2hlcikgcmV0dXJuOwogICAgY29uc3QgcHJvZ3Jlc3MgPSByZWFkUHJvZ3Jlc3MoKTsKICAgIGNvbnN0IGNvbXBsZXRlZCA9IHByb2dyZXNzPy5jb21wbGV0ZWQgPT09IHRydWU7CiAgICBsYXVuY2hlci5oaWRkZW4gPSBjb21wbGV0ZWQ7CiAgICBsYXVuY2hlci5zZXRBdHRyaWJ1dGUoImFyaWEtaGlkZGVuIiwgY29tcGxldGVkID8gInRydWUiIDogImZhbHNlIik7CiAgICBsYXVuY2hlci50ZXh0Q29udGVudCA9IHByb2dyZXNzICYmICFjb21wbGV0ZWQgPyAi5pON5L2c44Ks44Kk44OJ77yI57aa44GN44GL44KJ77yJIiA6ICLmk43kvZzjgqzjgqTjg4kiOwogIH0=', 'hide launcher after tutorial completion')
replace_once('tutorial.js', 'ICBmdW5jdGlvbiBzdGFydChpbmRleCA9IDApIHsKICAgIGlmICghc3RhdGUuc3RlcHMubGVuZ3RoKSByZXR1cm47CiAgICBzdGF0ZS5pbmRleCA9IGNsYW1wKE51bWJlcihpbmRleCkgfHwgMCwgMCwgc3RhdGUuc3RlcHMubGVuZ3RoIC0gMSk7CiAgICBzdGF0ZS5vcGVuID0gdHJ1ZTsKICAgIHJlbmRlclN0ZXAoKTsKICB9', 'ICBmdW5jdGlvbiBzdGFydChpbmRleCA9IDApIHsKICAgIGlmICghc3RhdGUuc3RlcHMubGVuZ3RoKSByZXR1cm47CiAgICBjb25zdCBsYXVuY2hlciA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJkcHJvLXR1dG9yaWFsLWxhdW5jaGVyIik7CiAgICBpZiAobGF1bmNoZXIpIHsKICAgICAgbGF1bmNoZXIuaGlkZGVuID0gZmFsc2U7CiAgICAgIGxhdW5jaGVyLnNldEF0dHJpYnV0ZSgiYXJpYS1oaWRkZW4iLCAiZmFsc2UiKTsKICAgIH0KICAgIHN0YXRlLmluZGV4ID0gY2xhbXAoTnVtYmVyKGluZGV4KSB8fCAwLCAwLCBzdGF0ZS5zdGVwcy5sZW5ndGggLSAxKTsKICAgIHN0YXRlLm9wZW4gPSB0cnVlOwogICAgcmVuZGVyU3RlcCgpOwogIH0=', 'allow explicit replay to reopen guide')
replace_once('tutorial.js', 'ICBmdW5jdGlvbiBza2lwKCkgewogICAgc2F2ZVByb2dyZXNzKHN0YXRlLnN0ZXBzW3N0YXRlLmluZGV4XT8uaWQgfHwgc3RhdGUuc3RlcHNbMF0/LmlkLCB0cnVlKTsKICAgIHVwZGF0ZUxhdW5jaGVyTGFiZWwoKTsKICAgIGNsb3NlKGZhbHNlKTsKICB9CgogIGZ1bmN0aW9uIGZpbmlzaCgpIHsKICAgIHNhdmVQcm9ncmVzcyhzdGF0ZS5zdGVwc1tzdGF0ZS5zdGVwcy5sZW5ndGggLSAxXT8uaWQsIHRydWUpOwogICAgdXBkYXRlTGF1bmNoZXJMYWJlbCgpOwogICAgY2xvc2UoZmFsc2UpOwogIH0=', 'ICBmdW5jdGlvbiBza2lwKCkgewogICAgc2F2ZVByb2dyZXNzKHN0YXRlLnN0ZXBzW3N0YXRlLmluZGV4XT8uaWQgfHwgc3RhdGUuc3RlcHNbMF0/LmlkLCB0cnVlKTsKICAgIGNsb3NlKGZhbHNlKTsKICAgIHVwZGF0ZUxhdW5jaGVyTGFiZWwoKTsKICB9CgogIGZ1bmN0aW9uIGZpbmlzaCgpIHsKICAgIHNhdmVQcm9ncmVzcyhzdGF0ZS5zdGVwc1tzdGF0ZS5zdGVwcy5sZW5ndGggLSAxXT8uaWQsIHRydWUpOwogICAgY2xvc2UoZmFsc2UpOwogICAgdXBkYXRlTGF1bmNoZXJMYWJlbCgpOwogIH0=', 'persist first-use dismissal')
